--[[ Tibia 8.31 ]]--

-- z-axis
Z_AXIS_DEFAULT = 7

-- statusbar
STATUSBAR_DURATION = 50 -- duration to show text

-- level spy
LEVELSPY_NOP_DEFAULT = 49451

LEVELSPY_ABOVE_DEFAULT = 7
LEVELSPY_BELOW_DEFAULT = 2

LEVELSPY_MIN = 0
LEVELSPY_MAX = 7

-- name spy
NAMESPY_NOP_DEFAULT  = 19061
NAMESPY_NOP2_DEFAULT = 16501

-- show invisible creatures
INVISIBLE1_DEFAULT = 114
INVISIBLE2_DEFAULT = 117

INVISIBLE_PATCH = 235

-- full light
LIGHT_NOP_DEFAULT = 1406

LIGHT_AMOUNT_DEFAULT = 128
LIGHT_AMOUNT_FULL    = 255

-- max
MAX_CREATURES     = 150 -- creatures in creature list
MAX_OUTFIT        = 301 -- highest possible outfit before client crashes
MAX_OUTFIT_COLORS = 132 -- possible outfit colors to choose

-- distances to step between addresses in memory
STEP_CREATURE = 160 -- creatures in creature list

-- offsets to variables from creature list step
OFFSET_CREATURE_ID           = 0   -- unique id
OFFSET_CREATURE_OUTFIT       = 96
OFFSET_CREATURE_OUTFIT_HEAD  = 100
OFFSET_CREATURE_OUTFIT_BODY  = 104
OFFSET_CREATURE_OUTFIT_LEGS  = 108
OFFSET_CREATURE_OUTFIT_FEET  = 112
OFFSET_CREATURE_OUTFIT_ADDON = 116

-- outfits

-- outfits that do not exist and cause the client to crash:
-- 0, 1, 135, 161-191, 302+
OUTFIT_ERROR =
{
    0, 1, 135,
    161, 162, 163, 164, 165, 166, 167, 168, 169, 170,
    171, 172, 173, 174, 175, 176, 177, 178, 179, 180,
    181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
    191
}

-- outfit as item:
-- set OFFSET_CREATURE_OUTFIT_HEAD to an item id
-- then set OFFSET_CREATURE_OUTFIT to OUTFIT_INVISIBLE
OUTFIT_INVISIBLE          = 0

OUTFIT_SWIMMING           = 267 -- swimming in water

OUTFIT_GAMEMASTER         = 75
OUTFIT_COMMUNITY_MANAGER  = 266

OUTFIT_HERO               = 73
OUTFIT_FERUMBRAS          = 229

OUTFIT_MALE_OLD           = 127 -- no animations
OUTFIT_FEMALE_OLD         = 126 -- no animations

OUTFIT_MALE_CITIZEN       = 128 -- druid
OUTFIT_MALE_HUNTER        = 129 -- paladin
OUTFIT_MALE_MAGE          = 130 -- sorcerer
OUTFIT_MALE_KNIGHT        = 131 -- knight

OUTFIT_MALE_NOBLEMAN      = 132
OUTFIT_MALE_SUMMONER      = 133
OUTFIT_MALE_WARRIOR       = 134
OUTFIT_MALE_BARBARIAN     = 143
OUTFIT_MALE_DRUID         = 144
OUTFIT_MALE_WIZARD        = 145
OUTFIT_MALE_ORIENTAL      = 146
OUTFIT_MALE_PIRATE        = 151
OUTFIT_MALE_ASSASSIN      = 152
OUTFIT_MALE_BEGGAR        = 153
OUTFIT_MALE_SHAMAN        = 154
OUTFIT_MALE_NORSEMAN      = 251
OUTFIT_MALE_NIGHTMARE     = 268
OUTFIT_MALE_JESTER        = 273
OUTFIT_MALE_BROTHERHOOD   = 278
OUTFIT_MALE_DEMONHUNTER   = 289

OUTFIT_FEMALE_CITIZEN     = 136 -- druid
OUTFIT_FEMALE_HUNTER      = 137 -- paladin
OUTFIT_FEMALE_SUMMONER    = 138 -- sorcerer
OUTFIT_FEMALE_KNIGHT      = 139 -- knight

OUTFIT_FEMALE_NOBLEMAN    = 140
OUTFIT_FEMALE_MAGE        = 141
OUTFIT_FEMALE_WARRIOR     = 142
OUTFIT_FEMALE_BARBARIAN   = 147
OUTFIT_FEMALE_DRUID       = 148
OUTFIT_FEMALE_WIZARD      = 149
OUTFIT_FEMALE_ORIENTAL    = 150
OUTFIT_FEMALE_PIRATE      = 155
OUTFIT_FEMALE_ASSASSIN    = 156
OUTFIT_FEMALE_BEGGAR      = 157
OUTFIT_FEMALE_SHAMAN      = 158
OUTFIT_FEMALE_NORSEMAN    = 252
OUTFIT_FEMALE_NIGHTMARE   = 269
OUTFIT_FEMALE_JESTER      = 270
OUTFIT_FEMALE_BROTHERHOOD = 279
OUTFIT_FEMALE_DEMONHUNTER = 288

-- outfit addons
OUTFIT_ADDON_NONE = 0
OUTFIT_ADDON_1    = 1
OUTFIT_ADDON_2    = 2
OUTFIT_ADDON_BOTH = 3

-- outfit colors
OUTFIT_COLORS_NEWBIE = {78, 69, 58, 76}
